clone:
  git:
    image: armswarmdrone/git

pipeline:
  build:
    image: quay.io/armswarm/golang:1.8-alpine
    environment:
      - CGO_ENABLED=0
    commands:
      - export OUTPUT_PATH=${PWD}
      - go get -d github.com/drone-plugins/drone-git
      - cd $GOPATH/src/github.com/drone-plugins/drone-git
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo
      - cp drone-git ${OUTPUT_PATH}

  docker:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/drone-git
    tag: [ "1.2", "1", "latest" ]
    when:
      branch: master
      event: push

  slack:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
